### ISSUE TITLE
/usr/bin/ld: cannot find -lnppi

### ISSUE THREAD

**Issue by ykosdev** [nourani/LBP#18]
Even though my .bashrc has 
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/:$LD_LIBRARY_PATH

it shows 
`-- Found CUDA: /usr/local/cuda-10.0 (found suitable exact version "10.0") 
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/phd/Downloads/LBP-master/build
[ 25%] Built target LBP
[ 50%] Built target LBPTest
[ 75%] Built target LBPMain
[ 87%] Linking CXX executable LBPGPU
/usr/bin/ld: cannot find -lnppi
collect2: error: ld returned 1 exit status
CMakeFiles/LBPGPU.dir/build.make:302: recipe for target 'LBPGPU' failed
make[2]: *** [LBPGPU] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/LBPGPU.dir/all' failed
make[1]: *** [CMakeFiles/LBPGPU.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by nourani** [comment]
You are missing the nppi library.

This is really old code and I'm not updating it anymore. Feel free to contribute with updates :)

**Comment by ykosdev** [comment]
for cuda 10 update

find_package(CUDA REQUIRED)
	set(CUDA_SEPARABLE_COMPILATION ON)
	set(CUDA_PROPAGATE_HOST_FLAGS ON)

	SET(CUDA_COMPILER "${CUDA_TOOLKIT_ROOT_DIR}/bin/nvcc")

TARGET_LINK_LIBRARIES(LBPGPU
		${CUDA_INCLUDE_DIRECTORIES}  X11 pthread
	)
