### ISSUE TITLE
LBPGPU  does not exist 

### ISSUE THREAD

**Issue by deter3** [nourani/LBP#8]
when I try to compile on mac , 

I got  

Make Error at CMakeLists.txt:79 (install):
  install TARGETS given target "LBPGPU" which does not exist in this
  directory.

I check LBPGPU is an option in CMakeLists , Can I compile without LBPGPU ?

**Comment by nourani** [comment]
Hi,
I have updated the CMakeList file. This should solve your issue. 

The problem was that you had chosen not to build the GPU code. As such, there was no GPU file to be installed.
